package interfaz;

import datos.Usuario;
import general.TipoUsuario;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.Serializable;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import ui.UIAplicacion;

/**
 *
 * @author Néstor Villalobos
 */
public class FRAdmin_Usuarios extends javax.swing.JFrame implements Serializable{

    //ATRIBUTOS
    private UIAplicacion ui;
    private Usuario administrador;
    private Usuario usuarioBuscado;
    //Flags
    private boolean crearActivado;
    private boolean modificarActivado;
    private boolean vistaActivado;
    private boolean camposHabilitados;

    //CONSTRUCTORES
    public FRAdmin_Usuarios(UIAplicacion ui, Usuario administrador) {
        initComponents();
        this.ui = ui;
        this.administrador = administrador;
        usuarioBuscado = null;
        crearActivado = true;
        modificarActivado = false;
        vistaActivado = false;
        camposHabilitados = true;
        interfaz();
    }

    //GETS&SETS
    public UIAplicacion getUi() {
        return ui;
    }

    public void setUi(UIAplicacion ui) {
        this.ui = ui;
    }
    
    public Usuario getAdministrador() {
        return administrador;
    }

    public void setAdministrador(Usuario administrador) {
        this.administrador = administrador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoUsuario = new javax.swing.ButtonGroup();
        pnlFondo = new javax.swing.JPanel();
        pnlTitular = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblMalla = new javax.swing.JLabel();
        lblCursos1 = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pnlTab = new javax.swing.JPanel();
        lblTabCrear = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        lblTabModificar = new javax.swing.JLabel();
        lblTabVista = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JFormattedTextField();
        pnlCrearModificar = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        btnCrearModificar = new javax.swing.JButton();
        scpTablaUsuarios = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        pnlInterno = new javax.swing.JPanel();
        lblTelefono = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblBuscar2 = new javax.swing.JLabel();
        rbEstudiante = new javax.swing.JRadioButton();
        rbAdministrador = new javax.swing.JRadioButton();
        lblTipo = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        lblEstado = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JFormattedTextField();
        txtTelefono = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setPreferredSize(new java.awt.Dimension(500, 600));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitular.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitular.setPreferredSize(new java.awt.Dimension(500, 40));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/skilltree_logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        lblLogo.setPreferredSize(new java.awt.Dimension(100, 30));

        lblMalla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMalla.setForeground(new java.awt.Color(153, 153, 153));
        lblMalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMalla.setText("Malla");
        lblMalla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMalla.setName("lblMenuMalla");
        lblMalla.setPreferredSize(new java.awt.Dimension(70, 30));
        lblMalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblCursos1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCursos1.setForeground(new java.awt.Color(153, 153, 153));
        lblCursos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCursos1.setText("Cursos");
        lblCursos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCursos1.setName("lblMenuCursos");
        lblCursos1.setPreferredSize(new java.awt.Dimension(70, 30));
        lblCursos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setText("Usuarios");
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios.setName("lblMenuUsuarios");
        lblUsuarios.setPreferredSize(new java.awt.Dimension(70, 30));
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tab.png"))); // NOI18N
        lblUsername.setText("Username");
        lblUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsername.setPreferredSize(new java.awt.Dimension(70, 30));
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTitularLayout = new javax.swing.GroupLayout(pnlTitular);
        pnlTitular.setLayout(pnlTitularLayout);
        pnlTitularLayout.setHorizontalGroup(
            pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitularLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTitularLayout.setVerticalGroup(
            pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMalla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlFondo.add(pnlTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTab.setBackground(new java.awt.Color(235, 235, 235));
        pnlTab.setPreferredSize(new java.awt.Dimension(500, 40));

        lblTabCrear.setBackground(new java.awt.Color(255, 255, 255));
        lblTabCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTabCrear.setForeground(new java.awt.Color(51, 51, 51));
        lblTabCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabCrear.setText("Crear");
        lblTabCrear.setAlignmentX(0.5F);
        lblTabCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTabCrear.setMaximumSize(new java.awt.Dimension(100, 30));
        lblTabCrear.setMinimumSize(new java.awt.Dimension(100, 30));
        lblTabCrear.setName("lblTabCrear");
        lblTabCrear.setOpaque(true);
        lblTabCrear.setPreferredSize(new java.awt.Dimension(100, 40));
        lblTabCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTabMouseClicked(evt);
            }
        });

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_buscar.png"))); // NOI18N
        lblBuscar.setAlignmentX(0.5F);
        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.setPreferredSize(new java.awt.Dimension(20, 30));
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });

        lblTabModificar.setBackground(new java.awt.Color(235, 235, 235));
        lblTabModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTabModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabModificar.setText("Modificar");
        lblTabModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTabModificar.setName("lblTabModificar");
        lblTabModificar.setOpaque(true);
        lblTabModificar.setPreferredSize(new java.awt.Dimension(100, 40));
        lblTabModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTabMouseClicked(evt);
            }
        });

        lblTabVista.setBackground(new java.awt.Color(235, 235, 235));
        lblTabVista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTabVista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabVista.setText("Vista");
        lblTabVista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTabVista.setName("lblTabVista");
        lblTabVista.setOpaque(true);
        lblTabVista.setPreferredSize(new java.awt.Dimension(100, 40));
        lblTabVista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTabMouseClicked(evt);
            }
        });

        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtBuscar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscar.setToolTipText("Buscar usuario");
        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabLayout = new javax.swing.GroupLayout(pnlTab);
        pnlTab.setLayout(pnlTabLayout);
        pnlTabLayout.setHorizontalGroup(
            pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabLayout.createSequentialGroup()
                .addComponent(lblTabCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTabModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTabVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTabLayout.setVerticalGroup(
            pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabLayout.createSequentialGroup()
                .addGroup(pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTabModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTabCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTabVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlFondo.add(pnlTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        pnlCrearModificar.setBackground(new java.awt.Color(255, 255, 255));
        pnlCrearModificar.setLayout(null);

        lblMensaje.setForeground(new java.awt.Color(204, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setPreferredSize(new java.awt.Dimension(480, 20));
        pnlCrearModificar.add(lblMensaje);
        lblMensaje.setBounds(10, 11, 480, 20);

        btnCrearModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnCrearModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearModificar.setText("Crear");
        btnCrearModificar.setOpaque(false);
        btnCrearModificar.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCrearModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearModificarModificarActionPerformed(evt);
            }
        });
        pnlCrearModificar.add(btnCrearModificar);
        btnCrearModificar.setBounds(200, 450, 100, 40);

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        scpTablaUsuarios.setViewportView(tbUsuarios);

        pnlCrearModificar.add(scpTablaUsuarios);
        scpTablaUsuarios.setBounds(20, 390, 460, 40);

        pnlInterno.setBackground(new java.awt.Color(255, 255, 255));
        pnlInterno.setLayout(null);

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("Teléfono:");
        pnlInterno.add(lblTelefono);
        lblTelefono.setBounds(-23, 140, 120, 15);

        lblApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellido.setText("Apellido:");
        pnlInterno.add(lblApellido);
        lblApellido.setBounds(-23, 100, 120, 15);

        txtApellido.setPreferredSize(new java.awt.Dimension(235, 30));
        pnlInterno.add(txtApellido);
        txtApellido.setBounds(110, 90, 258, 29);

        txtNombre.setPreferredSize(new java.awt.Dimension(235, 30));
        pnlInterno.add(txtNombre);
        txtNombre.setBounds(110, 50, 258, 29);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        pnlInterno.add(lblNombre);
        lblNombre.setBounds(-23, 60, 120, 15);

        lblIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdentificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdentificacion.setText("Identificación:");
        pnlInterno.add(lblIdentificacion);
        lblIdentificacion.setBounds(-23, 20, 120, 15);

        lblBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_buscar_grnd.png"))); // NOI18N
        lblBuscar2.setAlignmentX(0.5F);
        lblBuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar2.setPreferredSize(new java.awt.Dimension(20, 30));
        lblBuscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscar2MouseClicked(evt);
            }
        });
        pnlInterno.add(lblBuscar2);
        lblBuscar2.setBounds(380, 10, 30, 30);

        rbEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        btngTipoUsuario.add(rbEstudiante);
        rbEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbEstudiante.setSelected(true);
        rbEstudiante.setText("Estudiante");
        pnlInterno.add(rbEstudiante);
        rbEstudiante.setBounds(210, 175, 83, 23);

        rbAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        btngTipoUsuario.add(rbAdministrador);
        rbAdministrador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbAdministrador.setText("Administrador");
        pnlInterno.add(rbAdministrador);
        rbAdministrador.setBounds(110, 175, 99, 23);

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipo.setText("Tipo:");
        pnlInterno.add(lblTipo);
        lblTipo.setBounds(-23, 180, 120, 15);

        chkActivo.setBackground(new java.awt.Color(255, 255, 255));
        chkActivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkActivo.setText("Activo");
        pnlInterno.add(chkActivo);
        chkActivo.setBounds(110, 205, 66, 23);

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado:");
        pnlInterno.add(lblEstado);
        lblEstado.setBounds(-23, 210, 120, 15);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuario:");
        pnlInterno.add(lblUsuario);
        lblUsuario.setBounds(-23, 250, 120, 15);

        txtUsuario.setEditable(false);
        txtUsuario.setPreferredSize(new java.awt.Dimension(235, 30));
        pnlInterno.add(txtUsuario);
        txtUsuario.setBounds(110, 240, 258, 29);

        lblContrasena.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblContrasena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContrasena.setText("Contraseña:");
        pnlInterno.add(lblContrasena);
        lblContrasena.setBounds(-23, 290, 120, 15);
        pnlInterno.add(txtContrasena);
        txtContrasena.setBounds(110, 280, 260, 30);

        try {
            txtIdentificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIdentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdentificacionMouseClicked(evt);
            }
        });
        pnlInterno.add(txtIdentificacion);
        txtIdentificacion.setBounds(110, 10, 260, 30);

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlInterno.add(txtTelefono);
        txtTelefono.setBounds(110, 130, 260, 30);

        pnlCrearModificar.add(pnlInterno);
        pnlInterno.setBounds(40, 30, 420, 350);

        pnlFondo.add(pnlCrearModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearModificarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearModificarModificarActionPerformed
        String id = txtIdentificacion.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String telefono = txtTelefono.getText();
        String contrasena = txtContrasena.getText();
        TipoUsuario tipo;
        if (rbAdministrador.isSelected()) {
            tipo = TipoUsuario.Administrador;
        } else {
            tipo = TipoUsuario.Estudiante;
        }
        boolean activo = chkActivo.isSelected();

        //TAB VISTA ACTIVADA
        if (vistaActivado) {
            int cualFila = tbUsuarios.getSelectedRow();
            Usuario u = ui.getRegUsuarios().getListaUsuarios().get(cualFila);
            buscarUsuario(u.getId());
            return;
        }

        if (!camposVacios()) {
            //TAB CREAR ACTIVADA
            if (crearActivado) {
                if (ui.crearUsuario(id, nombre, apellido, telefono, tipo, true)) {
                    lblMensaje.setText("Usuario creado. Su contraseña y nombre de usuario han sido creados automáticamente.");
                    lblMensaje.setForeground(Color.black);
                    
                    Usuario usuario = ui.buscarUsuario(id);
                    usuario.setMalla(ui.sincronizarMallaEstudiante(usuario));
                    limpiar();
                } else {
                    lblMensaje.setText("El usuario ya existe. Escriba una identificación diferente.");
                    lblMensaje.setForeground(Color.red);
                }
            }
            //TAB MODIFICAR ACTIVADA
            if (modificarActivado) {
                Usuario usuarioTemp = usuarioBuscado;
                if (rbAdministrador.isSelected() && !id.equals(usuarioTemp.getId())){
                    if (ui.buscarUsuario(id) == null){
                        ui.modificarAdministrador(usuarioTemp.getId(), id, nombre, apellido, telefono, tipo, activo, contrasena);
                        lblMensaje.setText("Usuario modificado.");
                        lblMensaje.setForeground(Color.black);
                    } 
                    else{
                        lblMensaje.setText("La nueva identificación ya esta asiganada. Utilice una diferente.");
                        lblMensaje.setForeground(Color.red);
                        usuarioBuscado = usuarioTemp;
                    }                    
                }
                else{
                    ui.modificarUsuario(id, nombre, apellido, telefono, tipo, activo, contrasena);
                    lblMensaje.setText("Usuario modificado.");
                    lblMensaje.setForeground(Color.black);
                }                
            }
        } else {
            lblMensaje.setText("Por favor complete todos los campos.");
            lblMensaje.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnCrearModificarModificarActionPerformed

    private void lblBuscar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscar2MouseClicked
        String id = txtIdentificacion.getText();
        buscarUsuario(id);
    }//GEN-LAST:event_lblBuscar2MouseClicked

    private void txtIdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdentificacionMouseClicked
        if (modificarActivado && camposHabilitados && !rbAdministrador.isSelected()) {
            camposHabilitados = false;
            limpiar();
            interfaz();
        }
    }//GEN-LAST:event_txtIdentificacionMouseClicked

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            String id = txtBuscar.getText();
            buscarUsuario(id);
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        String id = txtBuscar.getText();
        buscarUsuario(id);
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        if (tbUsuarios.getSelectedRow() != -1) {
            camposHabilitados = true;
        } else {
            camposHabilitados = false;
        }
        interfaz();
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void lblTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTabMouseClicked
        limpiar();
        lblMensaje.setText(null);
        crearActivado = false;
        modificarActivado = false;
        vistaActivado = false;
        camposHabilitados = false;

        JLabel tab = (JLabel) evt.getSource();
        if (tab.getName().equals("lblTabCrear")) {
            crearActivado = true;
            camposHabilitados = true;
        } else if (tab.getName().equals("lblTabModificar")) {
            modificarActivado = true;
        } else if (tab.getName().equals("lblTabVista")) {
            vistaActivado = true;
            cargarTablaUsuarios();
        }
        interfaz();
    }//GEN-LAST:event_lblTabMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        JLabel tab = (JLabel) evt.getSource();
        if (tab.getName().equals("lblMenuUsuarios")) {
        } else if (tab.getName().equals("lblMenuCursos")) {
            FRAdmin_Cursos ventana = new FRAdmin_Cursos(this.ui, this.administrador);
            ventana.show();
            this.dispose();
        } else if (tab.getName().equals("lblMenuMalla")) {
            FRAdmin_Malla ventana = new FRAdmin_Malla(this.ui, this.administrador);
            ventana.show();
            this.dispose();
        }
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        FRLogin ventana = new FRLogin(this.ui);
        ventana.show();
        this.dispose();
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered

        lblUsername.setText("Salir");
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tab_on.png")));        
        lblUsername.setForeground(Color.white);

}//GEN-LAST:event_lblUsernameMouseEntered

private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
    lblUsername.setText(administrador.getLogin());
    lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tab.png")));
    lblUsername.setForeground(new Color(153, 153, 153));
}//GEN-LAST:event_lblUsernameMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearModificar;
    private javax.swing.ButtonGroup btngTipoUsuario;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblBuscar2;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCursos1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMalla;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTabCrear;
    private javax.swing.JLabel lblTabModificar;
    private javax.swing.JLabel lblTabVista;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel pnlCrearModificar;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInterno;
    private javax.swing.JPanel pnlTab;
    private javax.swing.JPanel pnlTitular;
    private javax.swing.JRadioButton rbAdministrador;
    private javax.swing.JRadioButton rbEstudiante;
    private javax.swing.JScrollPane scpTablaUsuarios;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JFormattedTextField txtBuscar;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JFormattedTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    //OTROS MÉTODOS
    public void limpiar() {
        txtIdentificacion.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtContrasena.setText("");
        txtUsuario.setText("");
        txtBuscar.setText("Buscar usuario");
    }

    public boolean camposVacios() {
        if(crearActivado){
            if (txtIdentificacion.getText().equals("")
                || txtNombre.getText().equals("")
                || txtApellido.getText().equals("")
                || txtTelefono.getText().equals("")) {
            return true;
            } else return false;
        }
        if(modificarActivado){
            if (txtIdentificacion.getText().equals("")
                || txtNombre.getText().equals("")
                || txtApellido.getText().equals("")
                || txtTelefono.getText().equals("")
                || txtContrasena.getText().equals("")) {
            return true;
            } else return false;
        }
        return false;
    }

    public void interfaz() {
        ///COLORES
        Color blanco = Color.white;
        Color gris = new Color(235, 235, 235);
        
        lblUsername.setText(administrador.getLogin());

        if (crearActivado) {
            btnCrearModificar.setText("Crear");

            //COLOR TABS
            lblTabCrear.setBackground(blanco);
            lblTabModificar.setBackground(gris);
            lblTabVista.setBackground(gris);

            //COORDENADAS
            txtIdentificacion.setBounds(110, 10, 260, 29);
            lblBuscar2.setBounds(380, 10, 30, 30);
        }

        if (modificarActivado) {
            btnCrearModificar.setText("Guardar");

            //COLOR TABS
            lblTabCrear.setBackground(gris);
            lblTabModificar.setBackground(blanco);
            lblTabVista.setBackground(gris);

            //COORDENADAS
            txtIdentificacion.setBounds(110, 10, 220, 29);
            lblBuscar2.setBounds(340, 10, 30, 30);
        }

        if (vistaActivado) {
            btnCrearModificar.setText("Detalle");
            pnlInterno.setVisible(false);
            scpTablaUsuarios.setBounds(20, 40, 460, 390);

            //COLOR TABS
            lblTabCrear.setBackground(gris);
            lblTabModificar.setBackground(gris);
            lblTabVista.setBackground(blanco);
        } else {
            pnlInterno.setVisible(true);
        }

        //VISIBILIDAD
        scpTablaUsuarios.setVisible(vistaActivado);
        lblUsuario.setVisible(modificarActivado);
        lblContrasena.setVisible(modificarActivado);
        lblBuscar2.setVisible(modificarActivado);
        txtContrasena.setVisible(modificarActivado);
        txtUsuario.setVisible(modificarActivado);
        lblEstado.setVisible(modificarActivado);
        chkActivo.setVisible(modificarActivado);

        //USABILIDAD
        txtNombre.setEnabled(camposHabilitados);
        txtApellido.setEnabled(camposHabilitados);
        txtTelefono.setEnabled(camposHabilitados);
        rbAdministrador.setEnabled(camposHabilitados);
        rbEstudiante.setEnabled(camposHabilitados);
        chkActivo.setEnabled(camposHabilitados);
        btnCrearModificar.setEnabled(camposHabilitados);
        txtContrasena.setEnabled(camposHabilitados);
    }

    private void cargarTablaUsuarios() {
        String[] rotulos = {"Identificación", "Nombre", "Teléfono", "Login", "Contraseña", "Tipo Usuario", "Estado"};
        DefaultTableModel dfm = new DefaultTableModel(rotulos, ui.getRegUsuarios().getListaUsuarios().size());

        int cont = 0;
        for (Usuario usr : ui.getRegUsuarios().getListaUsuarios()) {
            dfm.setValueAt(usr.getId(), cont, 0);
            dfm.setValueAt(usr.getNombre() + " " + usr.getApellido(), cont, 1);
            dfm.setValueAt(usr.getTelefono(), cont, 2);
            dfm.setValueAt(usr.getLogin(), cont, 3);
            dfm.setValueAt(usr.getContrasennia(), cont, 4);
            dfm.setValueAt(usr.getTipo(), cont, 5);
            dfm.setValueAt(usr.isActivo(), cont, 6);
            cont++;
        }
        tbUsuarios.setModel(dfm);
    }

    private void buscarUsuario(String id) {
        limpiar();
        lblMensaje.setText(null);
        modificarActivado = true;
        crearActivado = false;
        vistaActivado = false;
        camposHabilitados = false;
        interfaz();

        Usuario u = ui.buscarUsuario(id);
        usuarioBuscado = u;
        if (u != null) {
            camposHabilitados = true;
            interfaz();
            txtIdentificacion.setText(u.getId());
            txtNombre.setText(u.getNombre());
            txtApellido.setText(u.getApellido());
            txtTelefono.setText(u.getTelefono());
            if (u.getTipo() == TipoUsuario.Administrador) {
                rbAdministrador.setSelected(true);
            } else {
                rbEstudiante.setSelected(true);
            }
            chkActivo.setSelected(u.isActivo());
            txtUsuario.setText(u.getLogin());
            txtContrasena.setText(u.getContrasennia());
        } else {
            lblMensaje.setText("El usuario no ha sido encontrado.");
            lblMensaje.setForeground(Color.red);
        }
    }
}
