package interfaz;

import datos.Curso;
import datos.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.Serializable;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import ui.UIAplicacion;

/**
 *
 * @author Néstor Villalobos
 */
public class FRAdmin_Cursos extends javax.swing.JFrame implements Serializable{

    //ATRIBUTOS
    private UIAplicacion ui;
    private Usuario administrador;
    private Icon iconoSeleccionado;
    //Flags
    private boolean crearActivado;
    private boolean modificarActivado;
    private boolean vistaActivado;
    private boolean camposHabilitados;

    //CONSTRUCTORES
    public FRAdmin_Cursos(UIAplicacion ui, Usuario administrador) {
        initComponents();
        this.ui = ui;
        this.administrador = administrador;
        crearActivado = true;
        modificarActivado = false;
        vistaActivado = false;
        camposHabilitados = true;
        iconoSeleccionado = null;
        interfaz();
    }

    //GETS&SETS
    public UIAplicacion getUi() {
        return ui;
    }

    public void setUi(UIAplicacion ui) {
        this.ui = ui;
    }
    
    public Usuario getAdministrador() {
        return administrador;
    }

    public void setAdministrador(Usuario administrador) {
        this.administrador = administrador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoUsuario = new javax.swing.ButtonGroup();
        pnlFondo = new javax.swing.JPanel();
        pnlTitular = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblMalla = new javax.swing.JLabel();
        lblCursos1 = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pnlTab = new javax.swing.JPanel();
        lblTabCrear = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        lblTabModificar = new javax.swing.JLabel();
        txtBuscar1 = new javax.swing.JTextField();
        lblTabVista = new javax.swing.JLabel();
        txtBuscar2 = new javax.swing.JTextField();
        pnlCrearModificar = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        btnCrearModificar = new javax.swing.JButton();
        scpTablaCursos = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        pnlInterno = new javax.swing.JPanel();
        txtContenido = new javax.swing.JTextField();
        lblContenido = new javax.swing.JLabel();
        lblHoras = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        lblEstado = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        spnCreditos = new javax.swing.JSpinner();
        spnHoras = new javax.swing.JSpinner();
        btnExaminar = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        scpPanelIconos = new javax.swing.JScrollPane();
        pnlIconos = new javax.swing.JPanel();
        btnBoton1 = new javax.swing.JButton();
        btnBoton2 = new javax.swing.JButton();
        btnBoton3 = new javax.swing.JButton();
        btnBoton4 = new javax.swing.JButton();
        btnBoton5 = new javax.swing.JButton();
        btnBoton6 = new javax.swing.JButton();
        btnBoton7 = new javax.swing.JButton();
        btnBoton8 = new javax.swing.JButton();
        btnBoton9 = new javax.swing.JButton();
        btnBoton10 = new javax.swing.JButton();
        btnBoton11 = new javax.swing.JButton();
        btnBoton12 = new javax.swing.JButton();
        btnBoton13 = new javax.swing.JButton();
        btnBoton14 = new javax.swing.JButton();
        btnBoton15 = new javax.swing.JButton();
        btnBoton16 = new javax.swing.JButton();
        btnBoton17 = new javax.swing.JButton();
        btnBoton18 = new javax.swing.JButton();
        btnBoton19 = new javax.swing.JButton();
        btnBoton20 = new javax.swing.JButton();
        btnBoton21 = new javax.swing.JButton();
        btnBoton22 = new javax.swing.JButton();
        btnBoton23 = new javax.swing.JButton();
        btnBoton24 = new javax.swing.JButton();
        btnBoton25 = new javax.swing.JButton();
        btnBoton26 = new javax.swing.JButton();
        btnBoton27 = new javax.swing.JButton();
        btnBoton28 = new javax.swing.JButton();
        btnBoton29 = new javax.swing.JButton();
        btnBoton30 = new javax.swing.JButton();
        btnBoton31 = new javax.swing.JButton();
        btnBoton32 = new javax.swing.JButton();
        btnBoton33 = new javax.swing.JButton();
        btnBoton34 = new javax.swing.JButton();
        btnBoton35 = new javax.swing.JButton();
        btnBoton36 = new javax.swing.JButton();
        btnBoton37 = new javax.swing.JButton();
        lblBuscar2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setPreferredSize(new java.awt.Dimension(500, 600));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitular.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitular.setPreferredSize(new java.awt.Dimension(500, 40));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/skilltree_logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        lblLogo.setPreferredSize(new java.awt.Dimension(100, 30));

        lblMalla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMalla.setForeground(new java.awt.Color(153, 153, 153));
        lblMalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMalla.setText("Malla");
        lblMalla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMalla.setName("lblMenuMalla");
        lblMalla.setPreferredSize(new java.awt.Dimension(70, 30));
        lblMalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblCursos1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCursos1.setForeground(new java.awt.Color(255, 255, 255));
        lblCursos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCursos1.setText("Cursos");
        lblCursos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCursos1.setName("lblMenuCursos");
        lblCursos1.setPreferredSize(new java.awt.Dimension(70, 30));

        lblUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(153, 153, 153));
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setText("Usuarios");
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios.setName("lblMenuUsuarios");
        lblUsuarios.setPreferredSize(new java.awt.Dimension(70, 30));
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tab.png"))); // NOI18N
        lblUsername.setText("Username");
        lblUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsername.setPreferredSize(new java.awt.Dimension(70, 30));
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTitularLayout = new javax.swing.GroupLayout(pnlTitular);
        pnlTitular.setLayout(pnlTitularLayout);
        pnlTitularLayout.setHorizontalGroup(
            pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitularLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTitularLayout.setVerticalGroup(
            pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMalla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlFondo.add(pnlTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTab.setBackground(new java.awt.Color(235, 235, 235));
        pnlTab.setPreferredSize(new java.awt.Dimension(500, 40));

        lblTabCrear.setBackground(new java.awt.Color(255, 255, 255));
        lblTabCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTabCrear.setForeground(new java.awt.Color(51, 51, 51));
        lblTabCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabCrear.setText("Crear");
        lblTabCrear.setAlignmentX(0.5F);
        lblTabCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTabCrear.setMaximumSize(new java.awt.Dimension(100, 30));
        lblTabCrear.setMinimumSize(new java.awt.Dimension(100, 30));
        lblTabCrear.setName("lblTabCrear");
        lblTabCrear.setOpaque(true);
        lblTabCrear.setPreferredSize(new java.awt.Dimension(100, 40));
        lblTabCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTabMouseClicked(evt);
            }
        });

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_buscar.png"))); // NOI18N
        lblBuscar.setAlignmentX(0.5F);
        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.setPreferredSize(new java.awt.Dimension(20, 30));
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });

        lblTabModificar.setBackground(new java.awt.Color(235, 235, 235));
        lblTabModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTabModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabModificar.setText("Modificar");
        lblTabModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTabModificar.setName("lblTabModificar");
        lblTabModificar.setOpaque(true);
        lblTabModificar.setPreferredSize(new java.awt.Dimension(100, 40));
        lblTabModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTabMouseClicked(evt);
            }
        });

        txtBuscar1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtBuscar1.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar1.setText("Código");
        txtBuscar1.setToolTipText("Buscar curso");
        txtBuscar1.setPreferredSize(new java.awt.Dimension(140, 24));
        txtBuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscar1MouseClicked(evt);
            }
        });
        txtBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscar1KeyPressed(evt);
            }
        });

        lblTabVista.setBackground(new java.awt.Color(235, 235, 235));
        lblTabVista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTabVista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabVista.setText("Vista");
        lblTabVista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTabVista.setName("lblTabVista");
        lblTabVista.setOpaque(true);
        lblTabVista.setPreferredSize(new java.awt.Dimension(100, 40));
        lblTabVista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTabMouseClicked(evt);
            }
        });

        txtBuscar2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtBuscar2.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar2.setText("Nombre");
        txtBuscar2.setToolTipText("Buscar curso");
        txtBuscar2.setPreferredSize(new java.awt.Dimension(140, 24));
        txtBuscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscar2MouseClicked(evt);
            }
        });
        txtBuscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscar1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabLayout = new javax.swing.GroupLayout(pnlTab);
        pnlTab.setLayout(pnlTabLayout);
        pnlTabLayout.setHorizontalGroup(
            pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabLayout.createSequentialGroup()
                .addComponent(lblTabCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTabModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTabVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTabLayout.setVerticalGroup(
            pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabLayout.createSequentialGroup()
                .addGroup(pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTabModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTabCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTabVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlFondo.add(pnlTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        pnlCrearModificar.setBackground(new java.awt.Color(255, 255, 255));
        pnlCrearModificar.setLayout(null);

        lblMensaje.setForeground(new java.awt.Color(204, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setPreferredSize(new java.awt.Dimension(480, 20));
        pnlCrearModificar.add(lblMensaje);
        lblMensaje.setBounds(10, 11, 480, 20);

        btnCrearModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnCrearModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearModificar.setText("Crear");
        btnCrearModificar.setOpaque(false);
        btnCrearModificar.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCrearModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearModificarModificarActionPerformed(evt);
            }
        });
        pnlCrearModificar.add(btnCrearModificar);
        btnCrearModificar.setBounds(200, 450, 100, 40);

        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCursosMouseClicked(evt);
            }
        });
        scpTablaCursos.setViewportView(tbCursos);

        pnlCrearModificar.add(scpTablaCursos);
        scpTablaCursos.setBounds(20, 390, 460, 40);

        pnlInterno.setBackground(new java.awt.Color(255, 255, 255));
        pnlInterno.setLayout(null);
        pnlInterno.add(txtContenido);
        txtContenido.setBounds(110, 130, 170, 30);

        lblContenido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblContenido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContenido.setText("Contenido:");
        pnlInterno.add(lblContenido);
        lblContenido.setBounds(-23, 140, 120, 15);

        lblHoras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHoras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHoras.setText("Horas:");
        pnlInterno.add(lblHoras);
        lblHoras.setBounds(-23, 100, 120, 15);

        txtNombre.setPreferredSize(new java.awt.Dimension(235, 30));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoNombreMouseClicked(evt);
            }
        });
        pnlInterno.add(txtNombre);
        txtNombre.setBounds(110, 50, 258, 29);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        pnlInterno.add(lblNombre);
        lblNombre.setBounds(-23, 60, 120, 15);

        chkEstado.setBackground(new java.awt.Color(255, 255, 255));
        chkEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkEstado.setText("Incluido en la malla curricular");
        chkEstado.setEnabled(false);
        pnlInterno.add(chkEstado);
        chkEstado.setBounds(110, 270, 190, 23);

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado:");
        pnlInterno.add(lblEstado);
        lblEstado.setBounds(-23, 275, 120, 15);

        txtCodigo.setPreferredSize(new java.awt.Dimension(235, 30));
        txtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoNombreMouseClicked(evt);
            }
        });
        pnlInterno.add(txtCodigo);
        txtCodigo.setBounds(110, 10, 258, 29);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigo.setText("Código:");
        pnlInterno.add(lblCodigo);
        lblCodigo.setBounds(-23, 20, 120, 15);

        lblCreditos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCreditos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCreditos.setText("Créditos:");
        pnlInterno.add(lblCreditos);
        lblCreditos.setBounds(210, 100, 60, 15);

        spnCreditos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        pnlInterno.add(spnCreditos);
        spnCreditos.setBounds(280, 90, 90, 30);

        spnHoras.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        pnlInterno.add(spnHoras);
        spnHoras.setBounds(110, 90, 90, 30);

        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });
        pnlInterno.add(btnExaminar);
        btnExaminar.setBounds(293, 130, 77, 30);

        lblIcono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono.setText("Ícono:");
        pnlInterno.add(lblIcono);
        lblIcono.setBounds(-23, 180, 120, 15);

        scpPanelIconos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pnlIconos.setBackground(new java.awt.Color(255, 255, 255));

        btnBoton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_algebra.png"))); // NOI18N
        btnBoton1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_psicologia.png"))); // NOI18N
        btnBoton2.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_avion.png"))); // NOI18N
        btnBoton3.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_meta.png"))); // NOI18N
        btnBoton4.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_tags.png"))); // NOI18N
        btnBoton5.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_lab2.png"))); // NOI18N
        btnBoton6.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_interfaz.png"))); // NOI18N
        btnBoton7.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_joystick.png"))); // NOI18N
        btnBoton8.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_bases2.png"))); // NOI18N
        btnBoton9.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_bases3.png"))); // NOI18N
        btnBoton10.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_mercado.png"))); // NOI18N
        btnBoton11.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_pluma.png"))); // NOI18N
        btnBoton12.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_bombillo.png"))); // NOI18N
        btnBoton13.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_calculadora.png"))); // NOI18N
        btnBoton14.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_matematicas.png"))); // NOI18N
        btnBoton15.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_chip.png"))); // NOI18N
        btnBoton16.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_vs.png"))); // NOI18N
        btnBoton17.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_java2.png"))); // NOI18N
        btnBoton18.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_colores.png"))); // NOI18N
        btnBoton19.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_corazon.png"))); // NOI18N
        btnBoton20.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_cpu.png"))); // NOI18N
        btnBoton21.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_cuaderno.png"))); // NOI18N
        btnBoton22.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_dibujo.png"))); // NOI18N
        btnBoton23.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_ejecutivo.png"))); // NOI18N
        btnBoton24.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_personas.png"))); // NOI18N
        btnBoton25.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_error.png"))); // NOI18N
        btnBoton26.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_finanzas.png"))); // NOI18N
        btnBoton27.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_espectroVentana.png"))); // NOI18N
        btnBoton28.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_estadistica.png"))); // NOI18N
        btnBoton29.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_grafico2a.png"))); // NOI18N
        btnBoton30.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_grafico3.png"))); // NOI18N
        btnBoton31.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_mapa2.png"))); // NOI18N
        btnBoton32.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_lego.png"))); // NOI18N
        btnBoton33.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_lego2.png"))); // NOI18N
        btnBoton34.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_rubik.png"))); // NOI18N
        btnBoton35.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_smarthphone.png"))); // NOI18N
        btnBoton36.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        btnBoton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_iphone.png"))); // NOI18N
        btnBoton37.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBoton37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlIconosLayout = new javax.swing.GroupLayout(pnlIconos);
        pnlIconos.setLayout(pnlIconosLayout);
        pnlIconosLayout.setHorizontalGroup(
            pnlIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoton37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIconosLayout.setVerticalGroup(
            pnlIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBoton37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        scpPanelIconos.setViewportView(pnlIconos);

        pnlInterno.add(scpPanelIconos);
        scpPanelIconos.setBounds(110, 170, 260, 90);

        lblBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_buscar_grnd.png"))); // NOI18N
        lblBuscar2.setAlignmentX(0.5F);
        lblBuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar2.setPreferredSize(new java.awt.Dimension(20, 30));
        lblBuscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscar2MouseClicked(evt);
            }
        });
        pnlInterno.add(lblBuscar2);
        lblBuscar2.setBounds(380, 30, 30, 30);

        pnlCrearModificar.add(pnlInterno);
        pnlInterno.setBounds(40, 30, 420, 350);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setOpaque(false);
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 40));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarModificarActionPerformed(evt);
            }
        });
        pnlCrearModificar.add(btnEliminar);
        btnEliminar.setBounds(340, 450, 100, 40);

        pnlFondo.add(pnlCrearModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearModificarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearModificarModificarActionPerformed
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        int horas = (Integer) spnHoras.getValue();
        int creditos = (Integer) spnCreditos.getValue();
        String contenido = txtContenido.getText();
        boolean enUso = chkEstado.isSelected();

        //TAB VISTA ACTIVADA
        if (vistaActivado) {
            int cualFila = tbCursos.getSelectedRow();
            Curso c = getUi().getRegCursos().getListaCursos().get(cualFila);
            buscarCurso(c.getCodigo(), c.getNombre());
            return;
        }

        if (!camposVacios()) {
            //TAB CREAR ACTIVADA
            if (crearActivado) {
                if (getUi().crearCurso(codigo, nombre, horas, creditos, contenido, iconoSeleccionado)) {
                    lblMensaje.setText("Curso creado.");
                    lblMensaje.setForeground(Color.black);
                    limpiar();
                } else {
                    lblMensaje.setText("El curso ya existe. Escriba un código y/o nombre diferentes.");
                    lblMensaje.setForeground(Color.red);
                }
            }
            //TAB MODIFICAR ACTIVADA
            if (modificarActivado) {
                getUi().modificarCurso(codigo, nombre, horas, creditos, contenido, iconoSeleccionado, enUso);
                lblMensaje.setText("Curso modificado.");
                lblMensaje.setForeground(Color.black);
            }
        } else {
            lblMensaje.setText("Por favor complete todos los campos.");
            lblMensaje.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnCrearModificarModificarActionPerformed

    private void txtBuscar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar1KeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            String codigo = txtBuscar1.getText().trim();
            String nombre = txtBuscar2.getText().trim();
            buscarCurso(codigo, nombre);
        }
    }//GEN-LAST:event_txtBuscar1KeyPressed

    private void txtBuscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscar1MouseClicked
        txtBuscar1.setText("");
    }//GEN-LAST:event_txtBuscar1MouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        String codigo = txtBuscar1.getText().trim();
        String nombre = txtBuscar2.getText().trim();
        buscarCurso(codigo, nombre);
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void tbCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCursosMouseClicked
        if (tbCursos.getSelectedRow() != -1) {
            camposHabilitados = true;
        } else {
            camposHabilitados = false;
        }
        interfaz();
    }//GEN-LAST:event_tbCursosMouseClicked

    private void lblBuscar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscar2MouseClicked
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        buscarCurso(codigo, nombre);
    }//GEN-LAST:event_lblBuscar2MouseClicked

    private void txtBuscar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscar2MouseClicked
        txtBuscar2.setText("");
    }//GEN-LAST:event_txtBuscar2MouseClicked

    private void btnEliminarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarModificarActionPerformed
        if(!chkEstado.isSelected()){
            String codigo = txtCodigo.getText().trim();
            String nombre = txtNombre.getText().trim();
            if (getUi().eliminarCurso(codigo, nombre)) {
                lblMensaje.setText("Curso eliminado.");
                lblMensaje.setForeground(Color.black);
                camposHabilitados = false;
                limpiar();
                interfaz();
            } else {
                lblMensaje.setText("El curso no pudo ser eliminado.");
                lblMensaje.setForeground(Color.red);
            }
        }
        else {
            lblMensaje.setText("El curso no debe estar incluido en una malla curricular para poder ser eliminado.");
            lblMensaje.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_btnEliminarModificarActionPerformed

    private void lblTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTabMouseClicked
        limpiar();
        lblMensaje.setText(null);
        crearActivado = false;
        modificarActivado = false;
        vistaActivado = false;
        camposHabilitados = false;

        JLabel tab = (JLabel) evt.getSource();
        if (tab.getName().equals("lblTabCrear")) {
            crearActivado = true;
            camposHabilitados = true;
        } else if (tab.getName().equals("lblTabModificar")) {
            modificarActivado = true;
        } else if (tab.getName().equals("lblTabVista")) {
            vistaActivado = true;
            cargarTablaCursos();
        }
        interfaz();
    }//GEN-LAST:event_lblTabMouseClicked

    private void btnBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBotonMouseClicked
        JButton botonSeleccionado = (JButton) evt.getSource();
        iconoSeleccionado = botonSeleccionado.getIcon();
        deseleccionar();
        botonSeleccionado.setSelected(true);
    }//GEN-LAST:event_btnBotonMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        JLabel tab = (JLabel) evt.getSource();
        if (tab.getName().equals("lblMenuUsuarios")) {
            FRAdmin_Usuarios ventana = new FRAdmin_Usuarios(this.ui, this.administrador);
            ventana.show();
            this.dispose();
        } else if (tab.getName().equals("lblMenuCursos")) {
        } else if (tab.getName().equals("lblMenuMalla")) {
            FRAdmin_Malla ventana = new FRAdmin_Malla(this.ui, this.administrador);
            ventana.show();
            this.dispose();
        }
    }//GEN-LAST:event_lblMenuMouseClicked

    private void txtCodigoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoNombreMouseClicked
        if (modificarActivado && camposHabilitados) {
            camposHabilitados = false;
            limpiar();
            interfaz();
        }
    }//GEN-LAST:event_txtCodigoNombreMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        FRLogin ventana = new FRLogin(this.ui);
        ventana.setUi(ui);
        ventana.show();
        this.dispose();
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered

        lblUsername.setText("Salir");
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tab_on.png")));
        lblUsername.setForeground(Color.white);
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        lblUsername.setText(administrador.getLogin());
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tab.png")));
        lblUsername.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblUsernameMouseExited

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
        JFileChooser fc = new JFileChooser();
        int n = fc.showOpenDialog(this);
        if (n == JFileChooser.APPROVE_OPTION){
            txtContenido.setText(fc.getSelectedFile().getAbsolutePath());
        }
        else txtContenido.setText("N/A");
    }//GEN-LAST:event_btnExaminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton1;
    private javax.swing.JButton btnBoton10;
    private javax.swing.JButton btnBoton11;
    private javax.swing.JButton btnBoton12;
    private javax.swing.JButton btnBoton13;
    private javax.swing.JButton btnBoton14;
    private javax.swing.JButton btnBoton15;
    private javax.swing.JButton btnBoton16;
    private javax.swing.JButton btnBoton17;
    private javax.swing.JButton btnBoton18;
    private javax.swing.JButton btnBoton19;
    private javax.swing.JButton btnBoton2;
    private javax.swing.JButton btnBoton20;
    private javax.swing.JButton btnBoton21;
    private javax.swing.JButton btnBoton22;
    private javax.swing.JButton btnBoton23;
    private javax.swing.JButton btnBoton24;
    private javax.swing.JButton btnBoton25;
    private javax.swing.JButton btnBoton26;
    private javax.swing.JButton btnBoton27;
    private javax.swing.JButton btnBoton28;
    private javax.swing.JButton btnBoton29;
    private javax.swing.JButton btnBoton3;
    private javax.swing.JButton btnBoton30;
    private javax.swing.JButton btnBoton31;
    private javax.swing.JButton btnBoton32;
    private javax.swing.JButton btnBoton33;
    private javax.swing.JButton btnBoton34;
    private javax.swing.JButton btnBoton35;
    private javax.swing.JButton btnBoton36;
    private javax.swing.JButton btnBoton37;
    private javax.swing.JButton btnBoton4;
    private javax.swing.JButton btnBoton5;
    private javax.swing.JButton btnBoton6;
    private javax.swing.JButton btnBoton7;
    private javax.swing.JButton btnBoton8;
    private javax.swing.JButton btnBoton9;
    private javax.swing.JButton btnCrearModificar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.ButtonGroup btngTipoUsuario;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblBuscar2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContenido;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblCursos1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMalla;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTabCrear;
    private javax.swing.JLabel lblTabModificar;
    private javax.swing.JLabel lblTabVista;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel pnlCrearModificar;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlIconos;
    private javax.swing.JPanel pnlInterno;
    private javax.swing.JPanel pnlTab;
    private javax.swing.JPanel pnlTitular;
    private javax.swing.JScrollPane scpPanelIconos;
    private javax.swing.JScrollPane scpTablaCursos;
    private javax.swing.JSpinner spnCreditos;
    private javax.swing.JSpinner spnHoras;
    private javax.swing.JTable tbCursos;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtBuscar2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContenido;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    //OTROS MÉTODOS
    public void limpiar() {
        txtCodigo.setText("");
        txtNombre.setText("");
        spnHoras.setValue(0);
        spnCreditos.setValue(0);
        txtContenido.setText("");
        txtBuscar1.setText("Código");
        txtBuscar2.setText("Nombre");
        deseleccionar();
    }

    public boolean camposVacios() {
        if (txtCodigo.getText().equals("")
                || txtNombre.getText().equals("")
                || spnHoras.getValue().equals(0)
                || spnCreditos.getValue().equals(0)
                || txtContenido.getText().equals("")
                || iconoSeleccionado == null) {
            return true;
        } else {
            return false;
        }
    }

    public void interfaz() {
        ///COLORES
        Color blanco = Color.white;
        Color gris = new Color(235, 235, 235);
        
        lblUsername.setText(administrador.getLogin());

        if (crearActivado) {
            btnCrearModificar.setText("Crear");

            //COLOR TABS
            lblTabCrear.setBackground(blanco);
            lblTabModificar.setBackground(gris);
            lblTabVista.setBackground(gris);

            //COORDENADAS
            txtCodigo.setBounds(110, 10, 260, 29);
            txtNombre.setBounds(110, 50, 260, 29);
            lblBuscar2.setBounds(380, 30, 30, 30);
            btnCrearModificar.setBounds(200, 450, 100, 40);
            btnEliminar.setBounds(340, 450, 100, 40);
        }

        if (modificarActivado) {
            btnCrearModificar.setText("Guardar");

            //COLOR TABS
            lblTabCrear.setBackground(gris);
            lblTabModificar.setBackground(blanco);
            lblTabVista.setBackground(gris);

            //COORDENADAS
            txtCodigo.setBounds(110, 10, 220, 29);
            txtNombre.setBounds(110, 50, 220, 29);
            lblBuscar2.setBounds(340, 30, 30, 30);
            btnCrearModificar.setBounds(140, 450, 100, 40);
            btnEliminar.setBounds(280, 450, 100, 40);
        }

        if (vistaActivado) {
            btnCrearModificar.setText("Detalle");
            pnlInterno.setVisible(false);
            scpTablaCursos.setBounds(20, 40, 460, 390);

            //COLOR TABS
            lblTabCrear.setBackground(gris);
            lblTabModificar.setBackground(gris);
            lblTabVista.setBackground(blanco);

            //COORDENADAS
            btnCrearModificar.setBounds(200, 450, 100, 40);
            btnEliminar.setBounds(340, 450, 100, 40);
        } else {
            pnlInterno.setVisible(true);
        }

        //VISIBILIDAD
        lblEstado.setVisible(modificarActivado);
        lblBuscar2.setVisible(modificarActivado);
        chkEstado.setVisible(modificarActivado);
        scpTablaCursos.setVisible(vistaActivado);
        btnEliminar.setVisible(modificarActivado);

        //USABILIDAD
        txtContenido.setEnabled(camposHabilitados);
        spnHoras.setEnabled(camposHabilitados);
        spnCreditos.setEnabled(camposHabilitados);
        btnCrearModificar.setEnabled(camposHabilitados);
        btnEliminar.setEnabled(camposHabilitados);
        btnExaminar.setEnabled(camposHabilitados);

        Component[] componentesPnl = pnlIconos.getComponents();
        Component componente = null;
        for (int a = 0; a < componentesPnl.length; a++) {
            componente = componentesPnl[a];
            componente.setEnabled(camposHabilitados);
        }
    }

    private void cargarTablaCursos() {
        String[] rotulos = {"Código", "Nombre", "Horas", "Créditos", "Contenido", "Icono", "Estado"};
        DefaultTableModel dfm = new DefaultTableModel(rotulos, getUi().getRegCursos().getListaCursos().size());

        int cont = 0;
        for (Curso usr : getUi().getRegCursos().getListaCursos()) {
            dfm.setValueAt(usr.getCodigo(), cont, 0);
            dfm.setValueAt(usr.getNombre(), cont, 1);
            dfm.setValueAt(usr.getHoras(), cont, 2);
            dfm.setValueAt(usr.getCreditos(), cont, 3);
            dfm.setValueAt(usr.getContenidoTematico(), cont, 4);
            dfm.setValueAt(usr.getIcono().toString(), cont, 5);
            dfm.setValueAt(usr.isEnUso(), cont, 6);
            cont++;
        }
        tbCursos.setModel(dfm);
    }

    private void buscarCurso(String codigo, String nombre) {
        limpiar();
        lblMensaje.setText(null);
        modificarActivado = true;
        crearActivado = false;
        vistaActivado = false;
        camposHabilitados = false;
        interfaz();

        Curso c = getUi().buscarCurso(codigo, nombre);
        if (c != null) {
            camposHabilitados = true;
            interfaz();
            txtCodigo.setText(c.getCodigo());
            txtNombre.setText(c.getNombre());
            txtContenido.setText(c.getContenidoTematico());
            spnHoras.setValue(c.getHoras());
            spnCreditos.setValue(c.getCreditos());
            chkEstado.setSelected(c.isEnUso());
            
            if (chkEstado.isSelected()) {
                btnEliminar.setEnabled(false);
                lblMensaje.setText("Recuerde que un curso no puede ser eliminado si ha sido agregado a la malla curricular.");
                lblMensaje.setForeground(Color.black);
            }
            else if (!chkEstado.isSelected()) btnEliminar.setEnabled(true);
            
            Component[] componentesPnl = pnlIconos.getComponents();
            Component componente = null;
            for (int a = 0; a < componentesPnl.length; a++) {
                componente = componentesPnl[a];
                if (componente instanceof JButton) {
                    JButton botonSeleccionado = (JButton) componente;
                    if (botonSeleccionado.getIcon().equals(c.getIcono())) {
                        botonSeleccionado.setSelected(true);
                    }
                }
            }
        } else {
            lblMensaje.setText("El curso no ha sido encontrado.");
            lblMensaje.setForeground(Color.red);
        }
    }

    public void deseleccionar() {
        Component[] componentesPnl = pnlIconos.getComponents();
        Component componente = null;
        for (int a = 0; a < componentesPnl.length; a++) {
            componente = componentesPnl[a];
            if (componente instanceof JButton) {
                JButton botonSeleccionado = (JButton) componente;
                botonSeleccionado.setSelected(false);
            }
        }
    }
}
